on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      topics:
        description: 'Topic Name'
        required: true
        default: 'test-topic'
      kafka:
        description: 'Test scenario tags'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "Log level: ${{ github.event.inputs.topics }}"
        echo "Tags: ${{ github.event.inputs.kafka }}"
