on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    environment: staging
    name: A job to say hello
    env:
        FIRST_NAME: ${{secrets.MY_SECRET_VALUES}}
    steps:
    - name: Hello world action step
      id: hello
      uses: belay-gem/dev-js-actions@main
      with:
        who-to-greet: 'Nate Solomon'
      env:
        DEPLOY_ENV: ${{secrets.MY_SECRET_VALUES}}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{secrets.DEPLOY_ENV}} - ${{ steps.hello.outputs.time }}"
    - name: print environment variables
      run: env
    - name: print specific envt variables
      run: echo "${{env.FIRST_NAME}} - ${{secrets.DEPLOY_ENV}}"
