on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: belay-gem/dev-js-actions@main
      with:
        who-to-greet: 'Nate Solomon'
    - name: Action Setup
      with: # Set the secret as an input
        super_secret: ${{ secrets.MY_SECRET_VALUES }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.MY_SECRET_VALUES }}
    - name: print secrets
      run: echo "${{secrets.MY_SECRET_VALUES}} - ${{secrets.DEPLOY_ENV}}"
