name: Print some text every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        default: 'Periodically printing passages'
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      topics:
        description: 'Topic Name'
        required: true
        default: 'test-topic'
      kafka:
        description: 'Test scenario tags'


jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'Periodically printing passages' # here is the default message
        run: |
          echo "logLevel=${{ github.event.inputs.logLevel || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo "tags=${{ github.event.inputs.tags || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo "topics=${{ github.event.inputs.topics || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo "kafka=${{ github.event.inputs.kafka || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV

      - name: Print some text
        run: |
          echo "$logLevel" # prints the environmental variable, MESSAGE
          echo "$tags" # prints the environmental variable, MESSAGE
          echo "$topics" # prints the environmental variable, MESSAGE
          echo "$kafka" # prints the environmental variable, MESSAGE

      - name: Process it
        run: npm run start # prints the environmental variable, MESSAGE
